version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: 127.0.0.1:9200
    ports:
    - 5601:5601
