version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
    - 5601:5601
    networks:
    - esnet

 networks:
  esnet:
